[package]
name = "i_float"
version = "1.5.1"
authors = ["Nail Sharipov <nailxsharipov@gmail.com>"]
edition = "2021"
description = "This fixed float math library provides an efficient and deterministic solution for arithmetic and geometric operations."
license = "MIT"
repository = "https://github.com/iShape-Rust/iFloat"

[features]
default = []
glam = ["dep:glam"]

[dependencies]
serde = { version = "^1.0", features = ["derive"] }
glam = { optional = true, version = ">=0.27" }

[dev-dependencies]
rand = { version = "0.8.5", features = [] }