[package]
name = "i_float"
version = "0.9.0"
authors = ["Nail Sharipov <nailxsharipov@gmail.com>"]
edition = "2021"
description = "This fixed float math library provides an efficient and deterministic solution for arithmetic and geometric operations."
license = "MIT"
repository = "https://github.com/iShape-Rust/iFloat"

[dependencies]
serde = { version = "^1.0", features = ["derive"] }

[dev-dependencies]
rand = { version = "0.8.5", features = [] }